name: Issue Resolution

on:
  issues:
    types: [opened]  # Trigger on new issues
  issue_comment:
    types: [created]  # Trigger on new comments

jobs:
  resolve:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating branches and PRs
      issues: write    # Needed for commenting on issues
      pull-requests: write  # Needed for creating PRs
    
    steps:
      - name: Run Issue Resolution
        uses: laurigates/gha-issue-resolution@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          max-tokens: '8192'