"""Constants and types related to issue comments"""

# Command triggers
TRIGGER_PR_COMMENT = "/create-pr"
TRIGGER_UPDATE_COMMENT = "/update"

# Comment templates
ANALYSIS_TEMPLATE = """## AI-generated suggestion

Here's a potential solution to this issue, generated by an AI assistant:

{analysis}

To create a pull request with these changes, comment with: `{pr_trigger}`
To get an updated analysis, comment with: `{update_trigger}`

This is an AI-generated response and requires human validation and testing before implementation."""

RESPONSE_TEMPLATE = """## AI-generated response

{response}

To create a pull request with any code changes suggested above, comment with: `{pr_trigger}`
To get an updated analysis, comment with: `{update_trigger}`"""
